### ISSUE TITLE
[HANG] Game freeze while trying to place Miracle Matter/Terminal (Issue by certain seed and settings)

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#172]
**Original Title: [HANG] Game freeze while trying to place a save point (Issue by certain seed and settings)
Please go to [this comment](https://github.com/DoukutsuRandamu/IssueTracker/issues/172#issuecomment-3149814645) for more info**

**Describe the bug**
Follow-up on issue #105 and looks like the failsafe has failed. The game tried to place the save point but to no avail and just keeps on trying certain distances, repeated failures caused the game to hang and with stage debugging enabled, it floods `game.log`, attached below.

[game.log](https://github.com/user-attachments/files/20992920/game.log)
[seed.txt](https://github.com/user-attachments/files/20992925/seed.txt)

The seed is `13487365767704894925` however, a small bug is making the last 4-digits be different when viewing the sub-screen, to be actually read as `1348736576770489`**`5488`**. Now reported on #173.

You must use the former seed number shown, with the resolution set to Fullscreen, difficulty set to Hardened, Reinforced or Resonant and must collect Life Capsules to reach 14 HP before entering Depth 3. **To be done in one sitting, without continuing from a save. Very important that random size for maps is enabled!** Edit `config.json` and add `"debug" : true` and `"stage_debug" : true` and be sure to add `,` before the next line except when the next line is `}` Set `"RandomSizeMode"` to `true`.

**To Reproduce**
1. Download and place `seed.txt` to the folder where `Randamu.exe` is. Open `Randamu.exe` and start a run at a difficulty of Hardened, Reinforced or Resonant. (If resolution is not Fullscreen, go to General Options and set it, then close and reopen `Randamu.exe`.)
2. With debug enabled, proceed to the door to enter the next depth. **MUST** collect Life Capsules / 20 Stars to increase HP to 14 or more **BEFORE** entering Depth 3. (Caution: Entering Depth 7 places you right next to a Mimic on Resonant difficulty)
3. Upon entering Depth 9, the game freezes. With `"stage_debug" : true` enabled, `game.log` gets flooded.

**Version**
1.45.1.2 (may affect some previous versions)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.45.2.

**Comment by Fluff8836** [comment]
I reproduced the same issue on 1.45.2. Looks like the Save Point seems to have found a spot at distance of 113, but the game got stuck again. After miracle matter, could not proceed to hell objects. Here is the log file.

[game.log](https://github.com/user-attachments/files/21574931/game.log)

The reason I wanted it reopened is even though the save point part was fixed, the hang issue still persists with the Miracle Matter/Terminal placement. So, the steps to reproduce the issue on the opening comment can still be used. It will flood `game.log` a bit until it hits the "hard cap" which was distance 113. I believe at Depth 9 after the boss fight the game is also trying to place a Miracle Matter/Terminal on this. (Depends on seed and settings)

Please investigate the Miracle Matter/Terminal part where the writing of the `game.log` stopped when the game froze.
